composeexample/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tww/', include('tww.urls')),
]

tww/urls.py
from django.urls import path

from . import views

app_name = "tww"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("<int:random_index>/upload/", views.upload, name="upload"),
    path("all/", views.view_all_writings, name="view_all_writings"),
    path("<int:writing_id>/view/", views.view, name="view"),
]

tww/models.py
from django.db import models

# Create your models here.
class Mood(models.Model):
    mood_text = models.CharField(max_length=100)

    def __str__(self):
        return self.mood_text


class Writing(models.Model):
    writing_text = models.TextField(max_length=400)
    user_name = models.CharField(max_length=20)
    word1 = models.CharField(max_length=100)
    word2 = models.CharField(max_length=100)
    word3 = models.CharField(max_length=100)
    mood = models.ForeignKey(Mood, on_delete=models.CASCADE)

    def __str__(self):
        return self.writing_text

tww/views.py
from multiprocessing import context
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import random

from .models import Mood, Writing


def create(request):
    moods = Mood.objects.all()
    random_index = random.randint(0, len(moods) - 1)
    random_mood = moods[random_index].mood_text
    context = {"random_index": random_index, "random_mood": random_mood}
    return render(request, "tww/create.html", context)


def upload(request, random_index):
    moods = Mood.objects.all()
    w = Writing(
        writing_text=request.POST.get("writing-text"),
        user_name=request.POST.get("user-name"),
        word1="坊主",
        word2="屏風",
        word3="上手",
        mood=moods[random_index],
    )
    w.save()
    writing_id = w.id
    return HttpResponseRedirect(reverse("tww:view", args=(writing_id,)))


def view_all_writings(request):
    writings = Writing.objects.all()
    context = {"writings": writings}
    return render(request, "tww/view-all-writings.html", context)


def view(request, writing_id):
    writing = get_object_or_404(Writing, pk=writing_id)
    context = {"writing": writing}
    return render(request, "tww/view-writing.html", context)

tww/templates/tww/create.html
<p>キーワードは「単語１」，「単語２」，「単語３」です．{{ random_mood }}雰囲気で書きましょう．</p>
<form action="{% url 'tww:upload' random_index %}" method="post">
    {% csrf_token %}
    <textarea id="writing-text" name="writing-text" cols="100" rows="10"></textarea>
    <input type="text" id="user-name" name="user-name"></input>
    <input type="submit" value="作成">
</form>

tww/templates/tww/view-all-writings.html
<ul>
    {% for writing in writings %}
        <li>
            <p>{{ writing.writing_text }}</p>
            <p>作成者：{{ writing.user_name }}</p>
            <p>単語１：{{ writing.word1 }}</p>
            <p>単語２：{{ writing.word2 }}</p>
            <p>単語３：{{ writing.word3 }}</p>
            <p>雰囲気：{{ writing.mood }}</p>
        </li>
    {% endfor %}
</ul>

tww/templates/tww/view-writing.html
<p>{{ writing.writing_text }}</p>
<p>作成者：{{ writing.user_name }}</p>
<p>単語１：{{ writing.word1 }}</p>
<p>単語２：{{ writing.word2 }}</p>
<p>単語３：{{ writing.word3 }}</p>
<p>雰囲気：{{ writing.mood }}</p>